#!/bin/bash

sudo rm -rf /etc/bbqlinux-installer
sudo rm -rf /usr/bin/bbqlinux-installer
sudo rm -rf /usr/lib/bbqlinux-installer
sudo rm -rf /usr/share/bbqlinux-installer

pyrcc5 -o usr/share/bbqlinux-installer/qt_resources_rc.py usr/share/bbqlinux-installer/qt_resources.qrc

sudo cp -R usr /
sudo cp -R etc /

bbqlinux-installer $1
